Z3: update to v4.15.8
This release of Z3 seems to fix the bug in the Z3 bindings,
where BoolPtr and IntPtr are mismatched and reported an error as follows:

    java.lang.NoSuchFieldError: com.microsoft.z3.Native$BoolPtr.value I
    at com.microsoft.z3.Native.INTERNALfpaGetNumeralSign(Native Method)
    at com.microsoft.z3.Native.fpaGetNumeralSign(Native.java:7540)
    at org.sosy_lab.java_smt.solvers.z3.Z3FormulaCreator.getSign(Z3FormulaCreator.java:1043)
    ...